---
  lessons:
    - name: 'Γενική Φυσική Ι'
      semester: 1
      ects: 8
      code: 'ΓΘΥ201'
      type: 1
    - name: 'Γενικά Μαθηματικά Ι'
      semester: 1
      ects: 6
      code: 'ΜΑΥ201'
      type: 1
    - name: 'Εργαστήριο Εφαρμοσμένης Πληροφορικής'
      semester: 1
      code: 'ΗΥΥ501'
      type: 1
      ects: 5
    - name: 'Χημεία'
      semester: 1
      code: 'XMY201'
      type: 1
      ects: 5
    - name: 'Εφαρμοσμένα Μαθηματικά'
      semester: 1
      code: 'ΜΑΥ202'
      type: 1
      ects: 6
    - name: 'Γενικά Μαθηματικά ΙΙ'
      semester: 2
      code: 'ΜΑΥ203'
      type: 1
      ects: 6
    - name: 'Γενική Φυσική ΙΙ'
      semester: 2
      code: 'ΓΘΥ202'
      type: 1
      ects: 8
    - name: 'Γενικό Εργαστήριο'
      semester: 2
      code: 'ΓΘΥ501'
      type: 1
      ects: 5
    - name: 'Γενική Φυσική ΙΙΙ'
      semester: 2
      code: 'ΓΘΥ203'
      type: 1
      ects: 8
    - name: 'Προγραμματισμός Υπολογιστών & Υπολογιστική Φυσική'
      semester: 2
      code: 'ΗΥΥ201'
      type: 1
      ects: 5
    - name: 'Εργαστήριο Ηλεκτρικών Κυκλωμάτων'
      semester: 3
      code: 'ΕΦΥ501'
      type: 1
      ects: 5
    - name: 'Εφαρμοσμένα Μαθηματικά ΙΙ'
      semester: 3
      code: 'ΜΑΥ204'
      type: 1
      ects: 6
    - name: 'Φυσική Ατμόσφαιρας & Περιβάλλοντος'
      semester: 3
      code: 'ΑΠΥ201'
      type: 1
      ects: 5
    - name: 'Γενική Φυσική IV'
      semester: 3
      code: 'ΓΘΥ204'
      type: 1
      ects: 8
    - name: 'Γενικά Μαθηματικά ΙΙΙ'
      semester: 3
      code: 'ΜΑΥ206'
      type: 1
      ects: 6
    - name: 'Θεωρητική Μηχανική'
      semester: 4
      code: 'ΓΘΥ206'
      type: 1
      ects: 8
    - name: 'Μαθηματικές Μέθοδοι Φυσικής I'
      semester: 4
      code: 'ΜΑΥ205'
      type: 1
      ects: 6
    - name: 'Γενική Φυσική V'
      semester: 4
      code: 'ΓΘΥ205'
      type: 1
      ects: 8
    - name: 'Ηλεκτρονική'
      semester: 4
      code: 'ΗΤΥ201'
      type: 1
      ects: 5
    - name: 'Εργαστήριο Οπτικής'
      semester: 4
      code: 'ΓΘΥ502'
      type: 1
      ects: 4
    - name: 'Εργαστήριο Ηλεκτρονικής'
      semester: 5
      code: 'ΗΤΥ502'
      type: 1
      ects: 4
    - name: 'Κβαντομηχανική Ι'
      semester: 5
      code: 'ΓΘΥ207'
      type: 1
      ects: 8
    - name: 'Αστρονομία'
      semester: 5
      code: 'ΑΑΥ201'
      type: 1
      ects: 7
    - name: 'Πυρηνική Φυσική'
      semester: 5
      code: 'ΠΣY201'
      type: 1
      ects: 7
    - name: 'Εργαστήριο Aτομικής Φυσικής'
      semester: 5
      code: 'ΓΘΥ503'
      type: 1
      ects: 4
    - name: 'Ηλεκτρομαγνητισμός'
      semester: 6
      code: 'ΓΘΥ210'
      type: 1
      ects: 8
    - name: 'Κβαντομηχανική ΙΙ'
      semester: 6
      code: 'ΓΘΥ208'
      type: 1
      ects: 5
    - name: 'Στατιστική Φυσική'
      semester: 6
      code: 'ΓΘΥ209'
      type: 1
      ects: 7
    - name: 'Εργαστήριο Πυρηνικής Φυσικής Ι'
      semester: 6
      code: 'ΠΣΥ501'
      type: 1
      ects: 4
    - name: 'Εργαστήριο Δομής των Υλικών'
      semester: 6
      code: 'ΣΥΥ501'
      type: 1
      ects: 4
    - name: 'Φυσική Στερεάς Κατάστασης'
      semester: 7
      code: 'ΣΥΥ201'
      type: 1
      ects: 8
    - name: 'Αστροφυσική'
      semster: 7
      code: 'ΑΑΕ201'
      type: 2
      ects: 5
    - name: 'Φυσική Στοιχειωδών Σωματιδίων'
      semester: 7
      code: 'ΠΣΕ204'
      type: 2
      ects: 5
    - name: 'Ανανεώσιμες πηγές ενέργειας'
      semester: 7
      code: 'ΕΠΕ101'
      type: 2
      ects: 5
    - name: 'Ηλεκτρονικά Κυκλώματα'
      semester: 7
      code: 'ΗΤΕ203'
      type: 2
      ects: 5
    - name: 'Δομικές Ιδιότητες Στερεών'
      semester: 7
      code: 'ΣΥΕ203'
      type: 2
      ects: 5
    - name: 'Ατμοσφαιρικό Περιβάλλον'
      semester: 7
      code: 'ΑΠΕ202'
      type: 2
      ects: 5
    - name: 'Μη Γραμμικά Δυναμικά Συστήματα'
      semester: 7
      code: 'ΜΑΕ204'
      type: 2
      ects: 5
    - name: 'Υπολογιστική Φυσική και Εφαρμογές'
      semester: 7
      code: 'ΗΥΕ401'
      type: 2
      ects: 5
    - name: 'Εισαγωγή στη Διδακτική της Φυσικής'
      semester: 8
      code: 'ΔΨΕ401'
      type: 2
      ects: 5
    - name: 'Παρατηρησιακή Αστρονομία'
      semester: 8
      code: 'ΑΑΕ601'
      type: 2
      ects: 5
    - name: 'Πυρηνική Φυσική'
      semester: 8
      code: 'ΠΣΕ201'
      type: 2
      ects: 5
    - name: 'Θέματα Τηλεπικοινωνιών'
      semester: 8
      code: 'ΗΤΕ202'
      type: 2
      ects: 5
    - name: 'Φυσική Στερεάς Κατάστασης II'
      semester: 8
      code: 'ΣΥΕ207'
      type: 2
      ects: 5
    - name: 'Φυσική των Νανοδομών και Επιφανειών'
      semester: 8
      code: 'ΕΦΕ207'
      type: 2
      ects: 5
    - name: 'Χαμιλτονιανή Μηχανική'
      semester: 8
      code: 'ΓΘΕ202'
      type: 2
      ects: 5
    - name : 'Μετρολογία - Συστήματα Ποιότητας'
      semester: 7
      code: 'ΓΘE201'
      type: 3
      ects: 4
    - name: 'Ιατρική Φυσική- Δοσιμετρία'
      semester: 7
      code: 'ΒΙΕ102'
      type: 3
      ects: 4
    - name: 'Ιστορία και Εξέλιξη των Ιδεών στη Φυσική'
      semester: 7
      code: 'ΙΦE101'
      type: 3
      ects: 4
    - name: 'Εμβιοηλεκτρομαγνητισμός'
      semester: 7
      code: 'ΒΙΕ101'
      type: 3
      ects: 4
    - name: 'Φυσικοχημεία'
      semester: 7
      code: 'ΧΜΕ201'
      type: 3
      ects: 4
    - name: 'Φυσική των Μετάλλων'
      semester: 7
      code: 'ΣΥΕ201'
      type: 3
      ects: 4
    - name: 'Παραγωγή Ενέργειας από Πυρηνικές και Συμβατικές Πηγές'
      semester: 7
      code: 'ΕΠΕ202'
      type: 3
      ects: 4
    - name: 'Φυσική και Φιλοσοφία'
      semester: 7
      code: 'ΙΦΕ102'
      type: 3
      ects: 4
    - name: 'Ξένη Γλώσσα (Αγγλικά)'
      semester: 7
      code: 'ΓΛΕ201'
      type: 3
      ects: 4
    - name: 'Θέματα Εφαρμοσμένης Φυσικής'
      semester: 7
      code: 'ΕΦΕ201'
      type: 3
      ects: 4
    - name: 'Πρακτική Άσκηση'
      semester: 7
      code: 'ΑΜΕ501'
      type: 3
      ects: 4
    - name: 'Επιχειρηματικότητα και Καινοτομία Τεχνολογιών και Υλικών'
      semester: 8
      code: 'ΚΟE601'
      type: 3
      ects: 4
    - name: 'Τεχνικές Χαρακτηρισμού και Υλικά στη Συντήρηση Έργων Τέχνης'
      semester: 8
      code: 'EΦΕ205'
      type: 3
      ects: 4
    - name: 'Αριθμητική Ανάλυση'
      semester: 8
      code: 'ΜΑΕ203'
      type: 3
      ects: 4
    - name: 'Πιθανότητες - Στατιστική'
      semester: 8
      code: 'MAΕ201'
      type: 3
      ects: 4
    - name: 'Γεωφυσική – Σεισμολογία'
      semester: 8
      code: 'ΓΓΕ401'
      type: 3
      ects: 4
    - name: 'Κοσμική Ακτινοβολία'
      semester: 8
      code: 'ΠΣΕ203'
      type: 3
      ects: 4
    - name: 'Φυσική του Ανθρωπίνου Σώματος'
      semester: 8
      code: 'ΒΙΕ105'
      type: 3
      ects: 4
    - name: 'Γεωμετρική Οπτική - Εφαρμογές'
      semester: 8
      code: 'ΓΘΕ207'
      type: 3
      ects: 4
    - name: 'Βιολογία'
      semester: 8
      code: 'ΒΙE103'
      type: 3
      ects: 4
    - name: 'Φυσική των Υλικών'
      semester: 8
      code: 'ΣΥΕ202'
      type: 3
      ects: 4
    - name: 'Φυσική των Υλικών'
      semester: 8
      code: 'ΣΥΕ202'
      type: 3
      ects: 4
    - name: 'Μετεωρολογία'
      semester: 8
      code: 'ΑΠΕ201'
      type: 3
      ects: 4
    - name: 'Ηλεκτροακουστική'
      semester: 8
      code: 'ΕΦΕ204'
      type: 3
      ects: 4
    - name: 'Ραδιενέργεια Περιβάλλοντος'
      semester: 8
      code: 'ΠΣΕ202'
      type: 3
      ects: 4
    - name: 'Φωτονική και Εφαρμογές'
      semester: 8
      code: 'ΕΦΕ206'
      type: 3
      ects: 4
    - name: 'Χαοτική Δυναμική'
      semester: 8
      code: 'ΓΘΕ212'
      type: 3
      ects: 4
    - name: 'Μεθοδολογία, Παρουσίαση Θεμάτων Φυσικής'
      semester: 8
      code: 'ΑΜΕ201'
      type: 3
      ects: 4
    - name: 'Εργαστήριο Εκπαιδευτικής Τεχνολογίας'
      semester: 8
      code: 'ΔΨΕ502'
      type: 3
      ects: 4
    - name: 'Βιοφυσική'
      semester: 7
      code: 'ΒΙΕ103'
      type: 4
      ects: 4
    - name: 'Πλανητικά Συστήματα και Διαστημική Εξερεύνηση'
      semester: 7
      code: 'ΑΑΕ103'
      type: 4
      ects: 4
    - name: 'Εργαστήριο Πυρηνικής Φυσικής ΙΙ'
      semester: 7
      code: 'ΠΣΕ401'
      type: 4
      ects: 4
    - name: 'Γαλαξιακή και Εξωγαλαξιακή Αστρονομία'
      semester: 7
      code: 'ΑΑΕ202'
      type: 4
      ects: 4
    - name: 'Φυσική και Τεχνολογία Ημιαγωγικών Διατάξεων'
      semester: 7
      code: 'ΣΥΕ206'
      type: 4
      ects: 4
    - name: 'Θεωρητική Στατιστική Φυσική Στερεάς Κατάστασης'
      semester: 7
      code: 'ΓΘΕ206'
      type: 4
      ects: 4
    - name: 'Διάδοση Ηλεκτρομαγνητικών Κυμάτων και Εφαρμογές'
      semester: 7
      code: 'ΓΘΕ208'
      type: 4
      ects: 4
    - name: 'Γραμμικά Κυκλώματα'
      semester: 7
      code: 'ΕΦΕ202'
      type: 4
      ects: 4
    - name: 'Κρυσταλλοδομή και Εφαρμογές'
      semester: 7
      code: 'ΣΥΕ204'
      type: 4
      ects: 4
    - name: 'Μαγνητικά Υλικά και Εφαρμογές'
      semester: 7
      code: 'ΣΥΕ205'
      type: 4
      ects: 4
    - name: 'Μικροηλεκτρονική'
      semester: 7
      code: 'ΗΤΕ201'
      type: 4
      ects: 4
    - name: 'Κβαντομηχανική III'
      semester: 7
      code: 'ΓΘΕ205'
      type: 4
      ects: 4
    - name: 'Μαθηματικές μέθοδοι Φυσικής ΙΙ'
      semester: 7
      code: 'ΜΑΕ202'
      type: 4
      ects: 4
    - name: 'Ψηφιακά Συστήματα'
      semester: 7
      code: 'ΗΥΕ201'
      type: 4
      ects: 4
    - name: 'Εργαστήριο Διδακτικής της Φυσικής'
      semester: 7
      code: 'ΔΨΕ501'
      type: 4
      ects: 4
    - name: 'Πτυχιακή Εργασία-Εισαγωγή στην ερευνητική Μεθοδολογία'
      semester: 7
      code: 'ΑΜΕ701'
      type: 5
      ects: 8
    - name: 'Κοσμολογία'
      semester: 8
      code: 'ΑΑΕ102'
      type: 4
      ects: 4
    - name: 'Εισαγωγή στη Φυσική Ιονισμένων Αερίων (Φυσική Πλάσματος)'
      semester: 8
      code: 'ΓΘΕ211'
      type: 4
      ects: 4
    - name: 'Ραδιοαστρονομία – Αστρονομία σε Μη Οπτικά Μήκη Κύματος'
      semester: 8
      code: 'ΑΑΕ101'
      type: 4
      ects: 4
    - name: 'Θέματα Πυρηνικής θεωρίας'
      semester: 8
      code: 'ΠΣΕ101'
      type: 4
      ects: 4
    - name: 'Πειραματική Θεμελίωση της Φυσικής Στοιχειωδών Σωματιδίων'
      semester: 8
      code: 'ΠΣΕ207'
      type: 4
      ects: 4
    - name: 'Επιταχυντές και Ανιχνευτές στην Πυρηνική και Σωματιδιακή Φυσική'
      semester: 8
      code: 'ΠΣΕ206'
      type: 4
      ects: 4
    - name: 'Φυσική Ακτινοβολιών και Εφαρμογές Ραδιοϊσοτόπων'
      semester: 8
      code: 'ΒΙΕ201'
      type: 4
      ects: 4
    - name: 'Κβαντική Οπτική - Laser'
      semester: 8
      code: 'ΓΘΕ209'
      type: 4
      ects: 4
    - name: 'Ατμοσφαιρική Διάχυση και Διασπορά'
      semester: 8
      code: 'ΑΠΕ102'
      type: 4
      ects: 4
    - name: 'Παγκόσμιες Περιβαλλοντικές Μεταβολές'
      semester: 8
      code: 'ΕΠΕ101'
      type: 4
      ects: 4
    - name: 'Εργαστήριο Ηλεκτρονικών Κυκλωμάτων'
      semester: 8
      code: 'ΗΤΕ501'
      type: 4
      ects: 4
    - name: 'Προβλήματα Κβαντικής Φυσικής'
      semester: 8
      code: 'ΓΘΕ204'
      type: 4
      ects: 4
    - name: 'Μη Γραμμικά Κυκλώματα'
      semester: 8
      code: 'ΕΦΕ203'
      type: 4
      ects: 4
    - name: 'Γενική Θεωρία Σχετικότητας'
      semester: 8
      code: 'ΓΘΕ210'
      type: 4
      ects: 4
    - name: 'Αρχιτεκτονική Υπολογιστών'
      semester: 8
      code: 'ΗΥΕ202'
      type: 4
      ects: 4
    - name: 'Εργαστήριο Φυσικής Στερεάς Κατάστασης'
      semester: 8
      code: 'ΣΥΕ402'
      type: 4
      ects: 4
    - name: 'Μηχανική των Ρευστών'
      semester: 8
      code: 'ΓΘΕ211'
      type: 4
      ects: 4
